version: '3'

services:

    nginx:
        # 镜像
        image: nginx
        # 容器名
        container_name: nginx        
        # 端口
        ports:
            # 80 端口
            - "80:80"
            # 443 端口
            - "443:443"
        # 数据卷    
        volumes:
            # Nginx 配置文件夹
            - "./nginx/config:/etc/nginx/conf.d"
            # Nginx 站点的根目录
            - "./nginx/html:/html"
            # Nginx 日志文件夹
            - "./nginx/log:/log"
            # SSL 证书文件夹
            - "./nginx/ssl:/ssl"
        # 在容器退出时，总是重启容器    
        restart: always 

    bitwarden:
        # 镜像
        image: vaultwarden/server:latest
        # 容器名
        container_name: bitwarden        
        # 数据卷
        volumes:
            # Bitwarden 数据文件夹
            - ./bitwarden:/data           
        # 环境变量    
        environment:
            # 关闭用户注册
            - SIGNUPS_ALLOWED=false
            # 开启 Web 客户端
            - WEB_VAULT_ENABLED=true
            # Bitwarden 域名
            - DOMAIN=https://bitwarden.jianrry.com
        # 在容器退出时，总是重启容器    
        restart: always
       


         
