version: '3'

services: 

    nginx:
        # 镜像
        image: nginx
        # 容器名
        container_name: nginx                
        # 端口
        ports:
            # 80 端口
            - "80:80"
            # 443 端口
            - "443:443"
        # 数据卷    
        volumes:
            # Nginx 配置文件夹
            - "./nginx/config:/etc/nginx/conf.d"
            # Nginx 站点的根目录
            - "./nginx/html:/html"
            # Nginx 日志文件夹
            - "./nginx/log:/log"
            # SSL 证书文件夹
            - "./nginx/ssl:/ssl"
        # 在容器退出时，总是重启容器    
        restart: always 

    v2ray:
        # 镜像
        image: v2ray/official
        # 容器名
        container_name: v2ray                
        # 数据卷
        volumes:
            # V2Ray 配置文件
            - ./v2ray/config/config.json:/etc/v2ray/config.json
            # V2Ray 访问日志文件
            - ./v2ray/log/access.log:/var/log/v2ray/access.log
            # V2Ray 错误日志文件
            - ./v2ray/log/error.log:/var/log/v2ray/error.log                                                          
        # 在容器退出时，总是重启容器    
        restart: always     
       


         
