version: '3'

services:

    nginx:
        # 镜像
        image: nginx
        # 容器名
        container_name: nginx        
        # 端口
        ports:
            # 80 端口
            - "80:80"
            # 443 端口
            - "443:443"
        # 数据卷    
        volumes:
            # Nginx 配置文件夹
            - "./nginx/config:/etc/nginx/conf.d"
            # Nginx 站点的根目录
            - "./nginx/html:/html"
            # Nginx 日志文件夹
            - "./nginx/log:/log"
            # SSL 证书文件夹
            - "./nginx/ssl:/ssl"
        # 环境变量    
        environment:
            # 设置时区
            - TZ=Asia/Shanghai            
        # 在容器退出时，总是重启容器    
        restart: always

    chatgpt:
        # 镜像
        image: chenzhaoyu94/chatgpt-web:main
        # 容器名
        container_name: chatgpt         
        # 环境变量    
        environment:
            # API KEY
            - OPENAI_API_KEY=YOUR_API_KEY                    

       


         
