version: '3'

services:

    nginx:
        # 镜像
        image: nginx
        # 容器名
        container_name: nginx        
        # 端口
        ports:
            # 80 端口
            - "80:80"
            # 443 端口
            - "443:443"
        # 数据卷    
        volumes:
            # Nginx 配置文件夹
            - "./nginx/config:/etc/nginx/conf.d"
            # Nginx 站点的根目录
            - "./nginx/html:/html"
            # Nginx 日志文件夹
            - "./nginx/log:/log"
            # SSL 证书文件夹
            - "./nginx/ssl:/ssl"
        # 在容器退出时，总是重启容器    
        restart: always 

    qbittorrent:
        # 镜像    
        image: linuxserver/qbittorrent:14.3.9
        # 容器名        
        container_name: qbittorrent
        # 端口        
        ports:
            # TCP 端口
            - 6881:6881
            # UDP 端口
            - 6881:6881/udp        
        # 数据卷            
        volumes:
            # QBittorrent 配置文件夹
            - ./qbittorrent/config:/config
            # QBittorrent 下载文件夹
            - ./qbittorrent/downloads:/downloads
        # 环境变量        
        environment:
            # WebUI 端口（WebUI 用户名 admin 密码 adminadmin）
            - WEBUI_PORT=8080            
        # 容器退出时总是重启，但不考虑Docker守护进程启动时就已经停止的容器    
        restart: unless-stopped                    

             

       


         
